### ISSUE TITLE
link error with CUDA 3.1

### ISSUE THREAD

**Issue by edmundyan** [cudpp/cudpp#59]
_Original author: kashif.r...@gmail.com (June 27, 2010 16:27:27)_

<b>What steps will reproduce the problem?</b>
1. Update to cuda 3.1
2. Compile with cuda 3.1 nvcc
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
The linking should produce a shared lib. Instead get a linking error:
ld: duplicate symbol OperatorMin&lt;double&gt;::identity() constin ./cudpp_generated_scan_app.cu.o and ./cudpp_generated_compact_app.cu.o
collect2: ld returned 1 exit status
make[2]: **\* [lib/libcudpp.dylib] Error 1

<b>What version of the product are you using? On what operating system?</b>
1.1.1

<b>Please provide any additional information below.</b>
 Prior to the 3.1 release, nvcc treated **device** functions as implicitly static. This behavior has changed with the 3.1 release. As a result, the host linker will give a link error regarding multiple defined symbols, if two identical **device** functions are defined in two different compilations units. For example, when including function definitions through the #include &lt;&gt; mechanism; or a **device** function and an identical host function are defined in two different compilations units. 
For both cases, declaring the **device** function as static will make the compilation succeed.

_Original issue: http://code.google.com/p/cudpp/issues/detail?id=59_
